name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/hydro

            echo "🧹 Cleaning up Docker..."
            docker system prune -af

            echo "🔄 Pulling latest image..."
            /usr/local/bin/docker-compose pull

            echo "🚀 Restarting predictor service..."
            /usr/local/bin/docker-compose up -d predictor

            echo "✅ Flask predictor deployed!"
          EOF
